MONGO_DB_USER_NAME: test_user
MONGO_DB_PASSWORD: test_password
MONGO_DB_NAME: test_database
MONGO_DB_HOST: localhost
MONGO_DB_PORT: 27017
LOG_LEVEL: INFO
MONGO_DB_CONNECTION_TIMEOUT: 5000
MONGO_DB_READ_TIMEOUT: 5000
MONGO_DB_SERVER_SELECTION_TIMEOUT: 3000
